---
devices:
  midi:
    name: nanoKONTROL2 MIDI 1

synths:
  - type: sine
    freq: 16
    volume: 102

  - type: square
    freq: 17
    volume: 103

  - type: triangle
    freq: 18
    volume: 104

  - type: sawtooth
    freq: 19
    volume: 105

  -  type: passthrough
     volume: 107

mixers:
  default:
    Master:
      FRONT_LEFT: 108
      FRONT_RIGHT: 109
